### ISSUE TITLE
about csvGenerationCommand

### ISSUE THREAD

**Issue by ihrthk** [koral--/android-gradle-localization-plugin#15]
Assume i have a file in d:/language_append_CMSD_100_rev.xls ,How i use to about csvGenerationCommand? thanks.

**Comment by koral--** [comment]
You need some tool which is able to convert xls to csv and writes to standard output. In Linux and Mac OS X there is [catdoc](http://www.wagner.pp.ru/~vitus/software/catdoc/). In Windows (I guess you are using Windows) it might work under [Cygwin](https://cygwin.com/cgi-bin2/package-grep.cgi?grep=catdoc) but I haven't used it that way.
After you have working tool something like that should work:
`csvGenerationCommand=C:\\<path-to-xls2csv> d:\\language_append_CMSD_100_rev.xls`

PS. I keep in mind your pull request and direct XLS support will be done in the future.
