### ISSUE TITLE
Skip empty plural

### ISSUE THREAD

**Issue by sergioa** [koral--/android-gradle-localization-plugin#18]
What about applying allowEmptyTranslations to plurals? It is actually breaking my parsing since some of my language variants don't require specific translation to plurals.

**Comment by koral--** [comment]
Sure I can add this ASAP.
`allowEmptyTranslations` in context of strings means that one of the translations is empty (contains zero characters) while the others can be non-empty. Do you need that feature for plurals or you just want to have given plural translated only in some locales and absent in others so it will be taken from default locale (in other words you want non-translatable plural)?

**Comment by sergioa** [comment]
non-translatable plural would work indeed. thank you.
