### ISSUE TITLE
Are there any gradle command can display task properties?

### ISSUE THREAD

**Issue by ihrthk** [koral--/android-gradle-localization-plugin#19]
PS:In order to make  user of user the gradle plugin can be more conveniently and clearly to use the plugin.

Maybe Like this:

gradle -task localization properties
    
    File sourceFile
    File outRes;
    File inRes;
    Map<String, String> map;
    boolean append = true
    boolean replace = true
    File report;
    String csvFileURI
    String csvGenerationCommand
    ArrayList<String> ignorableColumns = []
    CSVStrategy csvStrategy
    String outputFileName = 'strings.xml'
    String outputIndent = '    '
    String name = "name";
    String translatable = "translatable";
    String comment = "comment"
    boolean skipInvalidName = true
    boolean skipDuplicatedName = true

**Comment by koral--** [comment]
There is built-in `gradle -q help --task <task_name>` but there are no help texts in sources. It is very good idea to add them.
