### ISSUE TITLE
gradle localization failed

### ISSUE THREAD

**Issue by ihrthk** [koral--/android-gradle-localization-plugin#20]
plugins {
    id "pl.droidsonroids.localization" version "1.0.8"
}

localization {
    xlsFile = file('language_iOS_append_ALL_343_RC_20150522v2.xlsx')
    allowEmptyTranslations = true
    defaultColumnName = "EN"
    name = "Android"
    ignorableColumns = ['WinPhone', 'iOS', 'END']
    outputDirectory file('outRes')
    sheetName "string table"
}

D:\studio_workspace\android\lite>gradle localization

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'lite'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve gradle.plugin.pl.droidsonroids.gradle.localization:android-gradle-localization-plugin:1.0.8.
     Required by:
         :lite:unspecified
      > Could not GET 'http://plugins.gradle.org/m2/gradle/plugin/pl/droidsonroids/gradle/localization/android-gradle-lo
calization-plugin/1.0.8/android-gradle-localization-plugin-1.0.8.pom'.
         > Connection to https://gradleware-plugins.s3.amazonaws.com refused

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by koral--** [comment]
`Connection to https://gradleware-plugins.s3.amazonaws.com refused` - that is problem with network connection. Gradle failed to download plugin from plugin repository. Currently that URL is reachable for me. Try again and/or check your network/firewall settings. 
You can also use another plugin inclusion syntax: https://github.com/koral--/android-gradle-localization-plugin#all-versions-of-gradle
