### ISSUE TITLE
column index instead of nameColumnName

### ISSUE THREAD

**Issue by a-klimashevsky** [koral--/android-gradle-localization-plugin#23]
Sometimes translators dont' use name for 'name column'. Also very often this is the first column.

The example:

 | en | fr | it | fi
---|---|---|---|---
text | en_text | fr_text | it_text | fi_text

Could you add option to use column index instead of column name ?

**Comment by koral--** [comment]
OK, good idea.

**Comment by koral--** [comment]
Done, sorry for the very long delay. `nameColumnIndex` has been added which can be used instead of `nameColumnName`.
Changes available in the `1.0.10-SNAPSHOT`
