### ISSUE TITLE
Error:Cause: pl/droidsonroids/gradle/localization/LocalizationPlugin : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by AAverin** [koral--/android-gradle-localization-plugin#29]
Error:Cause: pl/droidsonroids/gradle/localization/LocalizationPlugin : Unsupported major.minor version 52.0

**Comment by koral--** [comment]
See #21

**Comment by AAverin** [comment]
Android does not support Java8, using Java8 during compilation results in various compatibility and compilation issues.
Do you have a step by step guide on how to setup Java8 compilation so that it works on Android with your library?

**Comment by koral--** [comment]
Source and target compatibility can be set in `build.gradle` like this:
```
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
}
```
or even `VERSION_1_6`.

Are there still any issues with mentioned `compileOptions`?

**Comment by AAverin** [comment]
I have 1_7 compatablitiy set in my project, but as soon as I change JDK dir to Java 1.8 - I get an error ParseException: bad class file magic (cafebabe) or version (0034.0000).
All my investigation lead to a conclusion that no matter what settings are - you can't use 1.8 to build android projects stably.

**Comment by koral--** [comment]
OK, now plugin is copmiled using 1.7 target.
