### ISSUE TITLE
Default locale column not present

### ISSUE THREAD

**Issue by e-Joe** [koral--/android-gradle-localization-plugin#35]
When I try to run task after added new strings in spreadsheets , I am getting this error

* What went wrong:
Execution failed for task ':app:localization'.
> Default locale column not present

please, can somebody help me?

**Comment by koral--** [comment]
What is the input source? Local file, http(s) URL, XLS(X), CSV?

**Comment by e-Joe** [comment]
Google spreadsheet. It was working for me, but after I add new translations , I am getting this error. And also, can you explain me, what is Default locale column?

**Comment by e-Joe** [comment]
It was my fault, I change the name of default column in xls.
